### ISSUE TITLE
Add typing, always use range (not xrange)

### ISSUE THREAD

**Issue by ysangkok** [ricmoo/pyaes#20]
Would you accept a pull request by me to add typing and remove the xrange = range hack? Of course that would make pyaes inefficient on Python 2, but that is EOL anyway and people can use an old version.

**Comment by ricmoo** [comment]
What is the advantage of removing the `xrange = range` hack?

**Comment by ysangkok** [comment]
Type checking with Mypy could be made to work , I don't know how to do it
with xrange.

**Comment by ysangkok** [comment]
Closing since Python 2.7 is now out of support so there is no need to discuss this.
