### ISSUE TITLE
Error (a bytes-like object is required, not 'str')

### ISSUE THREAD

**Issue by victorTrofelli** [ricmoo/pyaes#33]
Hello, I'm having a problem with aes, every time I start debugging, I have an error saying that the key needs to be byte:
![Screenshot_2](https://user-images.githubusercontent.com/49568664/100237912-51999780-2f0e-11eb-88e5-8bc4cdef531d.png)

I followed all the steps in the example, but to no avail

**Comment by qiaohaoforever** [comment]
why did you close it, I have the same question~
