### ISSUE TITLE
Issue in blockfeeder?

### ISSUE THREAD

**Issue by tknorris** [ricmoo/pyaes#5]
When using your blockfeeder I frequently get an "invalid padding byte" on the last decrypter.feed() call to pick up the last decrypted block. I'm not an expert on AES or any of this code, but I think there is a bug here in the strip_PKCS7_padding method where it always treats a block as having padding when it may not (i.e. if the final decrypt resulted in a block of 16 bytes). Specifically, [here](https://github.com/ricmoo/pyaes/blob/master/pyaes/util.py#L57)

I think this should just return the data if the final byte is > chr(16)? I may be completely off on that though?

**Comment by tknorris** [comment]
Here's where strip_PKCS7_passing is always called on the last block: https://github.com/ricmoo/pyaes/blob/master/pyaes/blockfeeder.py#L60

**Comment by ricmoo** [comment]
That may very well be a bug. I will research it tonight. :)

**Comment by tknorris** [comment]
Thanks. After more research, what I've discovered (I think) is that PKCS7 padding is not mandatory for padding AES. Some people may simply pad with spaces or nulls at the end of the last block. In my particular case, the person encrypting the text was padding with nulls. To work around the issue, I changed the strip_PKCS7_padding method to just return the data if the pad is 0 or > 16. That's probably not the right fix though.

**Comment by ricmoo** [comment]
I think there are actually security concerns with padding with null... But it depends on the mode of operation whether you need padding or not, stream cipher modes like CTR do not require padding. If you are dealing with someone else's encrypted goop though, you are stuck decrypting it how they encrypted it.

Also make sure you understand: https://en.wikipedia.org/wiki/Padding_oracle_attack

**Comment by tknorris** [comment]
Thanks, as you mentioned though, in my case I'm not in control of the encryption so I can't control the padding. Maybe it should be possible to tell either the decryption/encryption mode or the block feeder what padding is being used?

**Comment by agriffis** [comment]
It seems like this bug conflated two issues: (1) whether ciphertext that's a multiple of 16 bytes needs to be padded, (2) what the padding should be. The former question is the original bug and I'm hitting it too. Are you interested in a PR to refrain from checking `data[-1]` if the ciphertext is a multiple of 16 bytes (and therefore unpadded)

**Comment by agriffis** [comment]
Oh wait, I see... Maybe padding is always required. However this code isn't reliably adding it for me:
```
    iv = b'1234567890123456'
    mode = pyaes.AESModeOfOperationCBC(key, iv=iv)
    encrypter = pyaes.Encrypter(mode)
    ciphertext = encrypter.feed(plaintext) + encrypter.feed()
```

**Comment by agriffis** [comment]
Oh gosh, in my case it's because I was using different keys in encrypt/decrypt. So maybe not a problem after all. Sorry for the noise.

**Comment by ricmoo** [comment]
One issue is that there are multiple ways to pad, 2 examples are PKCS#7 and Cipher Stealing... PKCS#7 will *always* add padding, if the data is a multiple of 16 bytes, then 16 bytes of \x10 is added, which means the empty string encrypted requires 16 bytes.

It also depends on the mode whether padding is even required, for example CTR mode doesn't require padding at all.

I was going to ask how you were using different keys for encryption vs. decryption, but now I understand... That was *the* bug. :)
