### ISSUE TITLE
Recent option to disable padding to block feeder broken code

### ISSUE THREAD

**Issue by zorro786** [ricmoo/pyaes#8]
I checked the code and you didn't change the arguments for _feed_stream function.

**Comment by ricmoo** [comment]
You are absolutely correct!

I've added the test cases and am just doing some final testing. I will release the fixed version shortly.

**Comment by ricmoo** [comment]
Thanks @zorro786!

I've added test cases for the stream API in the block feeder suite to help ensure this is not a problem in the future.

Please let me know if you have any further issues.

Thanks! :)

**Comment by zorro786** [comment]
Thanks!
